use crate::parser::{
    ActionProperty, AttachProperty, AttendeeProperty, CategoriesProperty, ClassificationProperty,
    CommentProperty, ContactProperty, CreatedProperty, DateTimeCompletedProperty,
    DateTimeDueProperty, DateTimeEndProperty, DateTimeStampProperty, DateTimeStartProperty,
    DescriptionProperty, DurationProperty, ExceptionDateTimesProperty, FreeBusyTimeProperty,
    GeographicPositionProperty, IanaProperty, LastModifiedProperty, LocationProperty,
    OrganizerProperty, PercentCompleteProperty, PriorityProperty, RecurrenceDateTimesProperty,
    RecurrenceIdProperty, RecurrenceRuleProperty, RelatedToProperty, RepeatCountProperty,
    RequestStatusProperty, ResourcesProperty, SequenceProperty, StatusProperty, SummaryProperty,
    TimeTransparencyProperty, TimeZoneIdProperty, TimeZoneNameProperty, TimeZoneOffsetProperty,
    TimeZoneUrlProperty, TriggerProperty, UniqueIdentifierProperty, UrlProperty, XProperty,
};

#[derive(Debug, PartialEq)]
pub enum ComponentProperty<'a> {
    DateTimeStamp(DateTimeStampProperty<'a>),
    UniqueIdentifier(UniqueIdentifierProperty<'a>),
    DateTimeStart(DateTimeStartProperty<'a>),
    Classification(ClassificationProperty<'a>),
    DateTimeCreated(CreatedProperty<'a>),
    Description(DescriptionProperty<'a>),
    GeographicPosition(GeographicPositionProperty<'a>),
    LastModified(LastModifiedProperty<'a>),
    Location(LocationProperty<'a>),
    Organizer(OrganizerProperty<'a>),
    Priority(PriorityProperty<'a>),
    Sequence(SequenceProperty<'a>),
    Status(StatusProperty<'a>),
    Summary(SummaryProperty<'a>),
    TimeTransparency(TimeTransparencyProperty<'a>),
    Url(UrlProperty<'a>),
    RecurrenceId(RecurrenceIdProperty<'a>),
    RecurrenceRule(RecurrenceRuleProperty<'a>),
    DateTimeEnd(DateTimeEndProperty<'a>),
    Duration(DurationProperty<'a>),
    Attach(AttachProperty<'a>),
    Attendee(AttendeeProperty<'a>),
    Categories(CategoriesProperty<'a>),
    Comment(CommentProperty<'a>),
    Contact(ContactProperty<'a>),
    ExceptionDateTimes(ExceptionDateTimesProperty<'a>),
    RequestStatus(RequestStatusProperty<'a>),
    RelatedTo(RelatedToProperty<'a>),
    Resources(ResourcesProperty<'a>),
    RecurrenceDateTimes(RecurrenceDateTimesProperty<'a>),
    DateTimeCompleted(DateTimeCompletedProperty<'a>),
    PercentComplete(PercentCompleteProperty<'a>),
    DateTimeDue(DateTimeDueProperty<'a>),
    FreeBusyTime(FreeBusyTimeProperty<'a>),
    TimeZoneId(TimeZoneIdProperty<'a>),
    TimeZoneUrl(TimeZoneUrlProperty<'a>),
    TimeZoneOffsetTo(TimeZoneOffsetProperty<'a>),
    TimeZoneOffsetFrom(TimeZoneOffsetProperty<'a>),
    TimeZoneName(TimeZoneNameProperty<'a>),
    Action(ActionProperty<'a>),
    Trigger(TriggerProperty<'a>),
    RepeatCount(RepeatCountProperty<'a>),
    XProperty(XProperty<'a>),
    IanaProperty(IanaProperty<'a>),
}
